export const US_STATES = [
  { slug: "california", name: "California", isCommProperty: true, alimonyName: "Spousal Support" },
  { slug: "texas", name: "Texas", isCommProperty: true, alimonyName: "Spousal Maintenance" },
  { slug: "new-york", name: "New York", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "florida", name: "Florida", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "illinois", name: "Illinois", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "pennsylvania", name: "Pennsylvania", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "ohio", name: "Ohio", isCommProperty: false, alimonyName: "Spousal Support" },
  { slug: "georgia", name: "Georgia", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "north-carolina", name: "North Carolina", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "michigan", name: "Michigan", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "new-jersey", name: "New Jersey", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "virginia", name: "Virginia", isCommProperty: false, alimonyName: "Spousal Support" },
  { slug: "washington", name: "Washington", isCommProperty: true, alimonyName: "Maintenance" },
  { slug: "arizona", name: "Arizona", isCommProperty: true, alimonyName: "Spousal Maintenance" },
  { slug: "massachusetts", name: "Massachusetts", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "tennessee", name: "Tennessee", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "indiana", name: "Indiana", isCommProperty: false, alimonyName: "Spousal Maintenance" },
  { slug: "missouri", name: "Missouri", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "maryland", name: "Maryland", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "wisconsin", name: "Wisconsin", isCommProperty: true, alimonyName: "Maintenance" },
  { slug: "colorado", name: "Colorado", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "minnesota", name: "Minnesota", isCommProperty: false, alimonyName: "Spousal Maintenance" },
  { slug: "south-carolina", name: "South Carolina", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "alabama", name: "Alabama", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "louisiana", name: "Louisiana", isCommProperty: true, alimonyName: "Permanent Periodic Alimony" },
  { slug: "kentucky", name: "Kentucky", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "oregon", name: "Oregon", isCommProperty: false, alimonyName: "Spousal Support" },
  { slug: "oklahoma", name: "Oklahoma", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "connecticut", name: "Connecticut", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "utah", name: "Utah", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "iowa", name: "Iowa", isCommProperty: false, alimonyName: "Spousal Support" },
  { slug: "nevada", name: "Nevada", isCommProperty: true, alimonyName: "Alimony" },
  { slug: "arkansas", name: "Arkansas", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "mississippi", name: "Mississippi", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "kansas", name: "Kansas", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "new-mexico", name: "New Mexico", isCommProperty: true, alimonyName: "Alimony" },
  { slug: "nebraska", name: "Nebraska", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "idaho", name: "Idaho", isCommProperty: true, alimonyName: "Alimony" },
  { slug: "west-virginia", name: "West Virginia", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "hawaii", name: "Hawaii", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "new-hampshire", name: "New Hampshire", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "maine", name: "Maine", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "rhode-island", name: "Rhode Island", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "montana", name: "Montana", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "delaware", name: "Delaware", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "south-dakota", name: "South Dakota", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "north-dakota", name: "North Dakota", isCommProperty: false, alimonyName: "Spousal Support" },
  { slug: "alaska", name: "Alaska", isCommProperty: false, alimonyName: "Alimony" },
  { slug: "vermont", name: "Vermont", isCommProperty: false, alimonyName: "Maintenance" },
  { slug: "wyoming", name: "Wyoming", isCommProperty: false, alimonyName: "Alimony" },
];

export const TR_CITIES = [
  { slug: "istanbul", name: "İstanbul" },
  { slug: "ankara", name: "Ankara" },
  { slug: "izmir", name: "İzmir" },
  { slug: "bursa", name: "Bursa" },
  { slug: "antalya", name: "Antalya" },
  { slug: "adana", name: "Adana" },
  { slug: "konya", name: "Konya" },
  { slug: "gaziantep", name: "Gaziantep" },
  { slug: "mersin", name: "Mersin" },
  { slug: "kayseri", name: "Kayseri" },
];

export const DE_STATES = [
  { slug: "berlin", name: "Berlin" },
  { slug: "hamburg", name: "Hamburg" },
  { slug: "muenchen", name: "München" },
  { slug: "bayern", name: "Bayern" },
  { slug: "nordrhein-westfalen", name: "Nordrhein-Westfalen" },
  { slug: "hessen", name: "Hessen" },
  { slug: "sachsen", name: "Sachsen" },
  { slug: "niedersachsen", name: "Niedersachsen" },
  { slug: "rheinland-pfalz", name: "Rheinland-Pfalz" },
  { slug: "sachsen-anhalt", name: "Sachsen-Anhalt" },
  { slug: "thueringen", name: "Thüringen" },
  { slug: "schleswig-holstein", name: "Schleswig-Holstein" },
  { slug: "saarland", name: "Saarland" },
  { slug: "mecklenburg-vorpommern", name: "Mecklenburg-Vorpommern" },
  { slug: "brandenburg", name: "Brandenburg" },
  { slug: "bremen", name: "Bremen" },
];
