import json

terms = {
  "en": {
    "title": "Terms of Service",
    "s1": "Acceptance",
    "s1_p": "By using SettleLens, you agree to these terms. If you do not agree, do not use the service.",
    "s2": "Service Description",
    "s2_warning": "IMPORTANT: SettleLens IS NOT LEGAL ADVICE. It provides financial modeling and scenario simulation only. Always consult a qualified attorney before making any decisions.",
    "s2_p": "SettleLens enables users to build and compare financial scenarios based on data they enter. Results are estimates and do not determine legal entitlements.",
    "s3": "User Accounts",
    "s3_li1": "You are responsible for maintaining the confidentiality of your account.",
    "s3_li2": "You must not share your account with others.",
    "s3_li3": "Users must be 18 years or older.",
    "s4": "Billing (Paddle)",
    "s4_p": "Payments are processed by Paddle, who acts as Merchant of Record. For billing issues, contact Paddle support.",
    "s5": "Cancellation & Refund",
    "s5_li1": "Monthly subscriptions (Strategist / Professional) can be cancelled anytime.",
    "s5_li2": "After cancellation, access continues until the end of the current period.",
    "s5_li3": "Clarified (one-time): refund may be requested within 7 days.",
    "s6": "Acceptable Use",
    "s6_p": "You may not use the service for illegal purposes, with others' data without consent, or to abuse the system.",
    "s7": "Intellectual Property",
    "s7_p": "The SettleLens platform and content are copyright protected. Data you enter remains yours.",
    "s8": "Disclaimer of Warranties",
    "s8_p": "The service is provided 'as is'. No warranty of accuracy, completeness, or fitness for a particular purpose.",
    "s9": "Limitation of Liability",
    "s9_p": "SettleLens liability is limited to the monthly fee you paid. We are not liable for indirect or consequential damages.",
    "s10": "Governing Law",
    "s10_p": "These terms are governed by Turkish law. Disputes shall be resolved in Istanbul courts.",
    "s11": "Changes",
    "s11_p": "We may update these terms. Material changes will be notified by email.",
  },
  "tr": {
    "title": "Kullanım Koşulları",
    "s1": "Kabul",
    "s1_p": "SettleLens'i kullanarak bu koşulları kabul etmiş olursunuz. Kabul etmiyorsanız hizmeti kullanmayınız.",
    "s2": "Hizmet Açıklaması",
    "s2_warning": "ÖNEMLİ: SettleLens HUKUKİ TAVSİYE DEĞİLDİR. Finansal modelleme ve senaryo simülasyonu sunar. Herhangi bir karar vermeden önce nitelikli bir avukata danışın.",
    "s2_p": "SettleLens, kullanıcıların kendi girdiği verilere dayalı finansal senaryolar oluşturmasına ve karşılaştırmasına olanak tanır. Sonuçlar tahmindir, yasal hakları belirlemez.",
    "s3": "Kullanıcı Hesapları",
    "s3_li1": "Hesap bilgilerinizin gizliliğinden siz sorumlusunuzdur.",
    "s3_li2": "Hesabınızı başkalarıyla paylaşmamalısınız.",
    "s3_li3": "18 yaş altı kişiler hizmeti kullanamaz.",
    "s4": "Faturalama (Paddle)",
    "s4_p": "Ödemeler Paddle tarafından işlenir. Paddle, Merchant of Record'dur. Fatura ve ödeme sorunları için Paddle müşteri hizmetlerine başvurun.",
    "s5": "İptal ve İade",
    "s5_li1": "Aylık abonelikler (Strategist / Professional) istediğiniz zaman iptal edilebilir.",
    "s5_li2": "İptal sonrası mevcut dönem sonuna kadar erişim devam eder.",
    "s5_li3": "Clarified (tek seferlik): 7 gün içinde iade talep edilebilir.",
    "s6": "Kabul Edilebilir Kullanım",
    "s6_p": "Hizmeti yasa dışı amaçlarla, başkalarının verilerini girerek veya sistemi kötüye kullanarak kullanamazsınız.",
    "s7": "Fikri Mülkiyet",
    "s7_p": "SettleLens platformu ve içeriği telif hakkıyla korunmaktadır. Girdiğiniz veriler size aittir.",
    "s8": "Garanti Reddi",
    "s8_p": "Hizmet 'olduğu gibi' sunulur. Sonuçların doğruluğu, eksiksizliği veya belirli bir amaca uygunluğu konusunda garanti verilmez.",
    "s9": "Sorumluluk Sınırlaması",
    "s9_p": "SettleLens'in sorumluluğu, ödediğiniz aylık ücretle sınırlıdır. Dolaylı veya sonuçsal zararlardan sorumlu değiliz.",
    "s10": "Geçerli Hukuk",
    "s10_p": "Bu koşullar Türkiye hukukuna tabidir. Anlaşmazlıklar İstanbul mahkemelerinde çözülür.",
    "s11": "Değişiklikler",
    "s11_p": "Koşulları değiştirebiliriz. Önemli değişikliklerde e-posta ile bildirim yapılır.",
  },
  "de": {
    "title": "Nutzungsbedingungen",
    "s1": "Annahme",
    "s1_p": "Durch die Nutzung von SettleLens stimmen Sie diesen Bedingungen zu.",
    "s2": "Leistungsbeschreibung",
    "s2_warning": "WICHTIG: SettleLens IST KEINE RECHTSBERATUNG. Es bietet Finanzmodellierung und Szenario-Simulation. Konsultieren Sie vor Entscheidungen einen qualifizierten Anwalt.",
    "s2_p": "SettleLens ermöglicht es Nutzern, Finanzszenarien basierend auf selbst eingegebenen Daten zu erstellen und zu vergleichen. Ergebnisse sind Schätzungen und bestimmen keine Rechtsansprüche.",
    "s3": "Benutzerkonten",
    "s3_li1": "Sie sind für die Vertraulichkeit Ihrer Kontoinformationen verantwortlich.",
    "s3_li2": "Sie dürfen Ihr Konto nicht teilen.",
    "s3_li3": "Personen unter 18 Jahren dürfen den Dienst nicht nutzen.",
    "s4": "Abrechnung (Paddle)",
    "s4_p": "Zahlungen werden von Paddle verarbeitet. Paddle ist Merchant of Record.",
    "s5": "Kündigung und Rückerstattung",
    "s5_li1": "Monatsabonnements (Strategist / Professional) können jederzeit gekündigt werden.",
    "s5_li2": "Nach Kündigung bleibt der Zugang bis zum Ende der aktuellen Periode bestehen.",
    "s5_li3": "Clarified (einmalig): Rückerstattung innerhalb von 7 Tagen möglich.",
    "s6": "Akzeptable Nutzung",
    "s6_p": "Sie dürfen den Dienst nicht für illegale Zwecke, mit Daten anderer oder durch Missbrauch des Systems nutzen.",
    "s7": "Geistiges Eigentum",
    "s7_p": "Die SettleLens-Plattform und deren Inhalte sind urheberrechtlich geschützt. Ihre eingegebenen Daten gehören Ihnen.",
    "s8": "Gewährleistungsausschluss",
    "s8_p": "Der Dienst wird 'wie besehen' bereitgestellt. Keine Garantie für Genauigkeit, Vollständigkeit oder Eignung für einen bestimmten Zweck.",
    "s9": "Haftungsbeschränkung",
    "s9_p": "Die Haftung von SettleLens ist auf den gezahlten Monatsbeitrag beschränkt.",
    "s10": "Anwendbares Recht",
    "s10_p": "Diese Bedingungen unterliegen türkischem Recht. Streitigkeiten werden vor Istanbuler Gerichten beigelegt.",
    "s11": "Änderungen",
    "s11_p": "Wir können die Bedingungen ändern. Bei wesentlichen Änderungen erfolgt eine E-Mail-Benachrichtigung.",
  },
  "fr": {
    "title": "Conditions d'utilisation",
    "s1": "Acceptation",
    "s1_p": "En utilisant SettleLens, vous acceptez ces conditions. Si vous n'acceptez pas, n'utilisez pas le service.",
    "s2": "Description du service",
    "s2_warning": "IMPORTANT : SettleLens N'EST PAS UN CONSEIL JURIDIQUE. Il fournit uniquement une modélisation financière et une simulation de scénarios. Consultez toujours un avocat qualifié avant de prendre des décisions.",
    "s2_p": "SettleLens permet aux utilisateurs de créer et de comparer des scénarios financiers basés sur les données qu'ils saisissent. Les résultats sont des estimations et ne déterminent pas les droits légaux.",
    "s3": "Comptes utilisateurs",
    "s3_li1": "Vous êtes responsable de la confidentialité de votre compte.",
    "s3_li2": "Vous ne devez pas partager votre compte avec d'autres personnes.",
    "s3_li3": "Les utilisateurs doivent avoir 18 ans ou plus.",
    "s4": "Facturation (Paddle)",
    "s4_p": "Les paiements sont traités par Paddle, qui agit en tant que Merchant of Record. Pour les problèmes de facturation, contactez le support Paddle.",
    "s5": "Annulation et remboursement",
    "s5_li1": "Les abonnements mensuels (Strategist / Professional) peuvent être annulés à tout moment.",
    "s5_li2": "Après l'annulation, l'accès continue jusqu'à la fin de la période en cours.",
    "s5_li3": "Clarified (paiement unique) : un remboursement peut être demandé dans les 7 jours.",
    "s6": "Utilisation acceptable",
    "s6_p": "Vous ne pouvez pas utiliser le service à des fins illégales, avec les données d'autres personnes sans consentement, ou pour abuser du système.",
    "s7": "Propriété intellectuelle",
    "s7_p": "La plateforme et le contenu de SettleLens sont protégés par le droit d'auteur. Les données que vous saisissez vous appartiennent.",
    "s8": "Exclusion de garantie",
    "s8_p": "Le service est fourni 'tel quel'. Aucune garantie d'exactitude, d'exhaustivité ou d'adéquation à un usage particulier.",
    "s9": "Limitation de responsabilité",
    "s9_p": "La responsabilité de SettleLens est limitée aux frais mensuels que vous avez payés. Nous ne sommes pas responsables des dommages indirects ou consécutifs.",
    "s10": "Droit applicable",
    "s10_p": "Ces conditions sont régies par le droit turc. Les litiges seront résolus devant les tribunaux d'Istanbul.",
    "s11": "Modifications",
    "s11_p": "Nous pouvons mettre à jour ces conditions. Les modifications importantes seront notifiées par e-mail.",
  },
  "es": {
    "title": "Términos de servicio",
    "s1": "Aceptación",
    "s1_p": "Al usar SettleLens, aceptas estos términos. Si no estás de acuerdo, no uses el servicio.",
    "s2": "Descripción del servicio",
    "s2_warning": "IMPORTANTE: SettleLens NO ES ASESORÍA LEGAL. Proporciona únicamente modelado financiero y simulación de escenarios. Consulta siempre a un abogado calificado antes de tomar decisiones.",
    "s2_p": "SettleLens permite a los usuarios crear y comparar escenarios financieros basados en los datos que ingresan. Los resultados son estimaciones y no determinan derechos legales.",
    "s3": "Cuentas de usuario",
    "s3_li1": "Eres responsable de mantener la confidencialidad de tu cuenta.",
    "s3_li2": "No debes compartir tu cuenta con otras personas.",
    "s3_li3": "Los usuarios deben tener 18 años o más.",
    "s4": "Facturación (Paddle)",
    "s4_p": "Los pagos son procesados por Paddle, quien actúa como Merchant of Record. Para problemas de facturación, contacta al soporte de Paddle.",
    "s5": "Cancelación y reembolso",
    "s5_li1": "Las suscripciones mensuales (Strategist / Professional) se pueden cancelar en cualquier momento.",
    "s5_li2": "Después de la cancelación, el acceso continúa hasta el final del período actual.",
    "s5_li3": "Clarified (pago único): se puede solicitar reembolso dentro de los 7 días.",
    "s6": "Uso aceptable",
    "s6_p": "No puedes usar el servicio para fines ilegales, con datos de otros sin consentimiento, o para abusar del sistema.",
    "s7": "Propiedad intelectual",
    "s7_p": "La plataforma y el contenido de SettleLens están protegidos por derechos de autor. Los datos que ingresas son tuyos.",
    "s8": "Exclusión de garantías",
    "s8_p": "El servicio se proporciona 'tal cual'. Sin garantía de exactitud, integridad o idoneidad para un propósito particular.",
    "s9": "Limitación de responsabilidad",
    "s9_p": "La responsabilidad de SettleLens se limita a la cuota mensual que pagaste. No somos responsables de daños indirectos o consecuentes.",
    "s10": "Ley aplicable",
    "s10_p": "Estos términos se rigen por la ley turca. Las disputas se resolverán en los tribunales de Estambul.",
    "s11": "Cambios",
    "s11_p": "Podemos actualizar estos términos. Los cambios materiales serán notificados por correo electrónico.",
  },
  "ar": {
    "title": "شروط الخدمة",
    "s1": "القبول",
    "s1_p": "باستخدام SettleLens، فإنك توافق على هذه الشروط. إذا كنت لا توافق، فلا تستخدم الخدمة.",
    "s2": "وصف الخدمة",
    "s2_warning": "مهم: SettleLens ليست استشارة قانونية. توفر فقط النمذجة المالية ومحاكاة السيناريوهات. استشر دائمًا محاميًا مؤهلًا قبل اتخاذ أي قرارات.",
    "s2_p": "يتيح SettleLens للمستخدمين إنشاء سيناريوهات مالية ومقارنتها بناءً على البيانات التي يدخلونها. النتائج تقديرات ولا تحدد الحقوق القانونية.",
    "s3": "حسابات المستخدمين",
    "s3_li1": "أنت مسؤول عن الحفاظ على سرية حسابك.",
    "s3_li2": "يجب ألا تشارك حسابك مع الآخرين.",
    "s3_li3": "يجب أن يكون المستخدمون 18 عامًا أو أكثر.",
    "s4": "الفوترة (Paddle)",
    "s4_p": "تتم معالجة المدفوعات بواسطة Paddle الذي يعمل بصفة Merchant of Record. للمشكلات المتعلقة بالفوترة، اتصل بدعم Paddle.",
    "s5": "الإلغاء والاسترداد",
    "s5_li1": "يمكن إلغاء الاشتراكات الشهرية (Strategist / Professional) في أي وقت.",
    "s5_li2": "بعد الإلغاء، يستمر الوصول حتى نهاية الفترة الحالية.",
    "s5_li3": "Clarified (دفعة واحدة): يمكن طلب الاسترداد خلال 7 أيام.",
    "s6": "الاستخدام المقبول",
    "s6_p": "لا يجوز استخدام الخدمة لأغراض غير قانونية أو ببيانات الآخرين دون موافقتهم أو لإساءة استخدام النظام.",
    "s7": "الملكية الفكرية",
    "s7_p": "منصة SettleLens ومحتواها محمية بحقوق النشر. البيانات التي تدخلها تبقى ملكًا لك.",
    "s8": "إخلاء المسؤولية عن الضمانات",
    "s8_p": "تُقدَّم الخدمة 'كما هي'. لا ضمان على الدقة أو الاكتمال أو الملاءمة لغرض معين.",
    "s9": "تحديد المسؤولية",
    "s9_p": "تقتصر مسؤولية SettleLens على الرسوم الشهرية التي دفعتها. لسنا مسؤولين عن الأضرار غير المباشرة أو التبعية.",
    "s10": "القانون الحاكم",
    "s10_p": "تخضع هذه الشروط للقانون التركي. تُحسم النزاعات أمام محاكم إسطنبول.",
    "s11": "التغييرات",
    "s11_p": "قد نحدّث هذه الشروط. سيتم إخطارك بالتغييرات الجوهرية عبر البريد الإلكتروني.",
  },
}

trust = {
  "en": {
    "title": "Built for One of Life's Most Sensitive Moments",
    "intro": "During divorce, people must share the most personal financial data of their lives. SettleLens is designed to earn and keep that trust.",
    "s1_title": "What We Collect and Why",
    "s1_li1": "Only what you enter: assets, debts, income, scenario data",
    "s1_li2": "If you consent: anonymous analytics (PostHog)",
    "s1_li3": "Never: advertising data, behavioral profiles",
    "s2_title": "How AI Analysis Works",
    "s2_p1": "AI is a calculator, not a judge. It analyzes your scenario, generates projections, and flags risk factors. It does not make decisions, predict outcomes, or speak on your behalf.",
    "s2_p2": "Your data is not stored at Anthropic and is not used for model training.",
    "s3_title": "What AI Does NOT Do",
    "s3_li1": "Does not predict court outcomes",
    "s3_li2": "Does not say \"accept\" or \"reject\" any offer",
    "s3_li3": "Does not provide legal advice",
    "s3_li4": "Does not suggest hiding or transferring assets",
    "s3_li5": "Does not say you don't need a lawyer",
    "s4_title": "Your Data Rights",
    "s4_export": "Export",
    "s4_export_link": "Settings → Privacy → Download JSON",
    "s4_delete": "Delete account",
    "s4_delete_link": "Settings → Privacy → Delete Account (permanent within 30 days)",
    "s4_gdpr": "GDPR and KVKK compliant by design.",
    "s5_title": "Payment Security",
    "s5_p": "Payments are processed by Paddle (Merchant of Record). Card details never reach SettleLens servers. Subscription management is handled in the Paddle portal.",
    "s6_title": "Who Can See Your Data",
    "s6_highlight": "No Anthropic employee, SettleLens team member, or third party has accessed your financial data. Only you can see your scenarios, assets, and reports.",
    "s6_rls": "Supabase Row Level Security: every query enforces auth.uid() = user_id.",
  },
  "tr": {
    "title": "Hayatın En Hassas Anlarından Biri İçin Tasarlandı",
    "intro": "Boşanma sürecinde insanlar hayatlarının en kişisel finansal verilerini paylaşmak zorunda kalır. SettleLens bu güveni hak etmek için tasarlanmıştır.",
    "s1_title": "Ne Topluyoruz ve Neden",
    "s1_li1": "Yalnızca siz girersiniz: varlık, borç, gelir, senaryo verileri",
    "s1_li2": "Onaylarsanız: anonim analitik (PostHog)",
    "s1_li3": "Hiçbir zaman: reklam verisi, davranışsal profil",
    "s2_title": "Yapay Zeka Nasıl Çalışır",
    "s2_p1": "Yapay zeka bir hesap makinesidir — hâkim değil. Senaryonuzu analiz eder, projeksiyonlar üretir, risk faktörlerini belirtir. Karar vermez, tahmin yapmaz, sizin adınıza konuşmaz.",
    "s2_p2": "Verileriniz Anthropic'te saklanmaz ve model eğitiminde kullanılmaz.",
    "s3_title": "Yapay Zekanın Yapmadıkları",
    "s3_li1": "Mahkeme sonucunu tahmin etmez",
    "s3_li2": "\"Teklifi kabul et/reddet\" demez",
    "s3_li3": "Hukuki tavsiye vermez",
    "s3_li4": "Varlık gizleme veya transfer önermez",
    "s3_li5": "\"Avukata gerek yok\" demez",
    "s4_title": "Veri Haklarınız",
    "s4_export": "Dışa aktarma",
    "s4_export_link": "Ayarlar → Gizlilik → JSON indir",
    "s4_delete": "Hesap silme",
    "s4_delete_link": "Ayarlar → Gizlilik → Hesabı Sil (30 gün içinde kalıcı)",
    "s4_gdpr": "GDPR ve KVKK kapsamında tasarlanmıştır.",
    "s5_title": "Ödeme Güvenliği",
    "s5_p": "Ödemeler Paddle tarafından işlenir (Merchant of Record). Kart bilgileri hiçbir zaman SettleLens sunucularına ulaşmaz. Abonelik yönetimi Paddle portalında yapılır.",
    "s6_title": "Verilerinizi Kim Görebilir",
    "s6_highlight": "Hiçbir Anthropic çalışanı, SettleLens ekip üyesi veya üçüncü taraf finansal verilerinize erişmemiştir. Senaryolarınızı, varlıklarınızı ve raporlarınızı yalnızca siz görebilirsiniz.",
    "s6_rls": "Supabase Row Level Security: her sorgu auth.uid() = user_id koşulunu zorunlu kılar.",
  },
  "de": {
    "title": "Für einen der sensibelsten Momente des Lebens",
    "intro": "In einer Scheidung müssen Menschen die persönlichsten Finanzdaten ihres Lebens teilen. SettleLens ist darauf ausgelegt, dieses Vertrauen zu verdienen und zu bewahren.",
    "s1_title": "Was wir sammeln und warum",
    "s1_li1": "Nur was Sie eingeben: Vermögen, Schulden, Einkommen, Szenariodaten",
    "s1_li2": "Bei Zustimmung: anonyme Analysen (PostHog)",
    "s1_li3": "Niemals: Werbedaten, Verhaltensprofile",
    "s2_title": "Wie die KI-Analyse funktioniert",
    "s2_p1": "Die KI ist ein Taschenrechner, kein Richter. Sie analysiert Ihr Szenario, erstellt Prognosen und kennzeichnet Risikofaktoren. Sie trifft keine Entscheidungen, sagt keine Ergebnisse voraus und spricht nicht in Ihrem Namen.",
    "s2_p2": "Ihre Daten werden nicht bei Anthropic gespeichert und nicht für das Training von Modellen verwendet.",
    "s3_title": "Was die KI NICHT tut",
    "s3_li1": "Sagt keine Gerichtsergebnisse voraus",
    "s3_li2": "Sagt nicht \"annehmen\" oder \"ablehnen\" für ein Angebot",
    "s3_li3": "Gibt keine Rechtsberatung",
    "s3_li4": "Schlägt nicht vor, Vermögen zu verstecken oder zu übertragen",
    "s3_li5": "Sagt nicht, dass Sie keinen Anwalt brauchen",
    "s4_title": "Ihre Datenrechte",
    "s4_export": "Exportieren",
    "s4_export_link": "Einstellungen → Datenschutz → JSON herunterladen",
    "s4_delete": "Konto löschen",
    "s4_delete_link": "Einstellungen → Datenschutz → Konto löschen (dauerhaft innerhalb von 30 Tagen)",
    "s4_gdpr": "DSGVO-konform by Design.",
    "s5_title": "Zahlungssicherheit",
    "s5_p": "Zahlungen werden von Paddle verarbeitet (Merchant of Record). Kartendaten erreichen niemals SettleLens-Server.",
    "s6_title": "Wer kann Ihre Daten sehen",
    "s6_highlight": "Kein Anthropic-Mitarbeiter, kein SettleLens-Teammitglied und keine dritte Partei hat auf Ihre Finanzdaten zugegriffen. Nur Sie können Ihre Szenarien, Vermögenswerte und Berichte sehen.",
    "s6_rls": "Supabase Row Level Security: Jede Abfrage erzwingt auth.uid() = user_id.",
  },
  "fr": {
    "title": "Conçu pour l'un des moments les plus sensibles de la vie",
    "intro": "Lors d'un divorce, les personnes doivent partager les données financières les plus personnelles de leur vie. SettleLens est conçu pour mériter et maintenir cette confiance.",
    "s1_title": "Ce que nous collectons et pourquoi",
    "s1_li1": "Uniquement ce que vous saisissez : actifs, dettes, revenus, données de scénarios",
    "s1_li2": "Si vous consentez : analyses anonymes (PostHog)",
    "s1_li3": "Jamais : données publicitaires, profils comportementaux",
    "s2_title": "Comment fonctionne l'analyse IA",
    "s2_p1": "L'IA est une calculatrice, pas un juge. Elle analyse votre scénario, génère des projections et signale les facteurs de risque. Elle ne prend pas de décisions, ne prédit pas les résultats et ne parle pas en votre nom.",
    "s2_p2": "Vos données ne sont pas stockées chez Anthropic et ne sont pas utilisées pour la formation des modèles.",
    "s3_title": "Ce que l'IA NE fait PAS",
    "s3_li1": "Ne prédit pas les résultats judiciaires",
    "s3_li2": "Ne dit pas \"accepter\" ou \"refuser\" une offre",
    "s3_li3": "Ne fournit pas de conseils juridiques",
    "s3_li4": "Ne suggère pas de cacher ou transférer des actifs",
    "s3_li5": "Ne dit pas que vous n'avez pas besoin d'un avocat",
    "s4_title": "Vos droits sur les données",
    "s4_export": "Exporter",
    "s4_export_link": "Paramètres → Confidentialité → Télécharger JSON",
    "s4_delete": "Supprimer le compte",
    "s4_delete_link": "Paramètres → Confidentialité → Supprimer le compte (définitif dans les 30 jours)",
    "s4_gdpr": "Conforme RGPD par conception.",
    "s5_title": "Sécurité des paiements",
    "s5_p": "Les paiements sont traités par Paddle (Merchant of Record). Les coordonnées de carte n'atteignent jamais les serveurs de SettleLens.",
    "s6_title": "Qui peut voir vos données",
    "s6_highlight": "Aucun employé d'Anthropic, aucun membre de l'équipe SettleLens ni aucun tiers n'a accédé à vos données financières. Seul vous pouvez voir vos scénarios, actifs et rapports.",
    "s6_rls": "Supabase Row Level Security : chaque requête applique auth.uid() = user_id.",
  },
  "es": {
    "title": "Diseñado para uno de los momentos más sensibles de la vida",
    "intro": "Durante un divorcio, las personas deben compartir los datos financieros más personales de sus vidas. SettleLens está diseñado para ganarse y mantener esa confianza.",
    "s1_title": "Qué recopilamos y por qué",
    "s1_li1": "Solo lo que tú ingresas: activos, deudas, ingresos, datos de escenarios",
    "s1_li2": "Si consientes: análisis anónimos (PostHog)",
    "s1_li3": "Nunca: datos publicitarios, perfiles de comportamiento",
    "s2_title": "Cómo funciona el análisis de IA",
    "s2_p1": "La IA es una calculadora, no un juez. Analiza tu escenario, genera proyecciones y señala factores de riesgo. No toma decisiones, no predice resultados ni habla en tu nombre.",
    "s2_p2": "Tus datos no se almacenan en Anthropic y no se usan para entrenar modelos.",
    "s3_title": "Lo que la IA NO hace",
    "s3_li1": "No predice resultados judiciales",
    "s3_li2": "No dice \"aceptar\" o \"rechazar\" ninguna oferta",
    "s3_li3": "No proporciona asesoramiento legal",
    "s3_li4": "No sugiere ocultar ni transferir activos",
    "s3_li5": "No dice que no necesitas un abogado",
    "s4_title": "Tus derechos sobre los datos",
    "s4_export": "Exportar",
    "s4_export_link": "Configuración → Privacidad → Descargar JSON",
    "s4_delete": "Eliminar cuenta",
    "s4_delete_link": "Configuración → Privacidad → Eliminar cuenta (permanente en 30 días)",
    "s4_gdpr": "Diseñado para cumplir con el RGPD.",
    "s5_title": "Seguridad de pagos",
    "s5_p": "Los pagos son procesados por Paddle (Merchant of Record). Los datos de tarjeta nunca llegan a los servidores de SettleLens.",
    "s6_title": "Quién puede ver tus datos",
    "s6_highlight": "Ningún empleado de Anthropic, miembro del equipo de SettleLens ni tercero ha accedido a tus datos financieros. Solo tú puedes ver tus escenarios, activos e informes.",
    "s6_rls": "Supabase Row Level Security: cada consulta aplica auth.uid() = user_id.",
  },
  "ar": {
    "title": "مصمم لأحد أكثر لحظات الحياة حساسية",
    "intro": "خلال الطلاق، يضطر الناس إلى مشاركة أكثر بياناتهم المالية خصوصية. صُمِّم SettleLens لاكتساب هذه الثقة والحفاظ عليها.",
    "s1_title": "ما نجمعه ولماذا",
    "s1_li1": "فقط ما تُدخله: الأصول والديون والدخل وبيانات السيناريوهات",
    "s1_li2": "عند موافقتك: تحليلات مجهولة الهوية (PostHog)",
    "s1_li3": "أبدًا: بيانات إعلانية أو ملفات تعريف سلوكية",
    "s2_title": "كيف يعمل تحليل الذكاء الاصطناعي",
    "s2_p1": "الذكاء الاصطناعي آلة حاسبة وليس قاضيًا. يحلل سيناريوهاتك ويُنشئ توقعات ويُشير إلى عوامل الخطر. لا يتخذ قرارات ولا يتنبأ بالنتائج ولا يتحدث نيابةً عنك.",
    "s2_p2": "لا يتم تخزين بياناتك في Anthropic ولا تُستخدم لتدريب النماذج.",
    "s3_title": "ما لا يفعله الذكاء الاصطناعي",
    "s3_li1": "لا يتنبأ بنتائج المحاكم",
    "s3_li2": "لا يقول \"اقبل\" أو \"ارفض\" أي عرض",
    "s3_li3": "لا يقدم مشورة قانونية",
    "s3_li4": "لا يقترح إخفاء أو نقل الأصول",
    "s3_li5": "لا يقول إنك لا تحتاج إلى محامٍ",
    "s4_title": "حقوقك في البيانات",
    "s4_export": "تصدير",
    "s4_export_link": "الإعدادات ← الخصوصية ← تنزيل JSON",
    "s4_delete": "حذف الحساب",
    "s4_delete_link": "الإعدادات ← الخصوصية ← حذف الحساب (دائم خلال 30 يومًا)",
    "s4_gdpr": "متوافق مع اللائحة الأوروبية GDPR بالتصميم.",
    "s5_title": "أمان المدفوعات",
    "s5_p": "تتم معالجة المدفوعات بواسطة Paddle (Merchant of Record). لا تصل تفاصيل البطاقة أبدًا إلى خوادم SettleLens.",
    "s6_title": "من يمكنه رؤية بياناتك",
    "s6_highlight": "لم يصل أي موظف في Anthropic أو عضو في فريق SettleLens أو طرف ثالث إلى بياناتك المالية. أنت وحدك من يمكنه رؤية سيناريوهاتك وأصولك وتقاريرك.",
    "s6_rls": "Supabase Row Level Security: كل استعلام يفرض auth.uid() = user_id.",
  },
}

base_path = "d:/girisimler/SettleLens/settlelens/messages"

for lang in ["en", "tr", "de", "fr", "es", "ar"]:
  filepath = f"{base_path}/{lang}.json"
  with open(filepath, "r", encoding="utf-8") as f:
    obj = json.load(f)
  obj["terms"] = terms[lang]
  obj["trust"] = trust[lang]
  with open(filepath, "w", encoding="utf-8") as f:
    json.dump(obj, f, ensure_ascii=False, indent=2)
  print(f"Updated {lang}.json")

print("All done")
